### ISSUE TITLE
Healing out of combat

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#10]
I currently have written up the following at this location:

https://github.com/basepi/akintu/wiki/Hit-points

HP is healed at the end of successful combat to 100%.  HP is not recovered automatically over time in the overworld if you were (for instance) injured by a fireball trap.  

Are these reasonable things?  Please discuss the matter on the Hit Points page.
@basepi @jabelch @Jzar

**Comment by malikoth** [comment]
The question of traps is an interesting one with regard to my suggestion of restoring all combat resources at the conclusion of combat.  (I don't remember specifically saying that includes health, but assume for the moment that it does)  Traditionally (I'm using this word waaaay too much, lol) you take some damage from an undiscovered trap, and you either sit and rest if you're too close to death for comfort, or just keep walking and regen health as you go because you're not in immediate danger of death anyways.

If health regen out of combat is simply accomplished by being healed at the end of combat, then there's no way to regen as you walk.  The trap could accomplish its purpose of threatening your life however, by leaving a debuff on you (like curses, as long as a buff / debuff system appears to be necessary for our game).  Say you get burned by a flame trap, now your constitution (and thus HP) is at -10% for 5 minutes.  Now you start combat with less health than normal, so the flame trap has changed your decisions in combat (if only sometimes), but you can't choose to just stop and heal it.

I don't know if this system has any advantages over the conventional model.  (See? An alternative to "Traditional"!  Yes!)  So I propose that we create a new derived stat called HP regen that is based on constitution that regenerates your health at a constant rate, in or out of combat.  (I have successfully kited strong monsters all the way around a dungeon level several times to give my passive HP regen time to bring me back up to fighting order in Moria)  Don't refill health at the conclusion of combat, and allow the health to fill up naturally over time.

**Comment by BlackVegetable** [comment]
I am open to an out-of-combat regeneration of health but I'd like to avoid it within combat.  I'm trying to make healing and especially regeneration a very special set of abilities.  I agree that such a derived stat should be based on Constitution.  I also agree that if we do have 100% restoration of health at the end of combat, we should primarily have traps that give debuffs (or outright kill you if your max hp is pitifully low for the level-area you are exploring.)

**Comment by basepi** [comment]
I'd be fine with the systems described by either @Jzar or @BlackVegetable.

I don't have strong feelings on this one.

**Comment by basepi** [comment]
Except NO REQUIRED EATING TO RESTORE HEALTH.  (I'm looking at YOU, WoW)

**Comment by jabelch** [comment]
Ha! Use a shovel to dig up some roots or something... didn't your mother tell you to eat your veggies?... or starches?

I don't want in battle regen either, at least not automatically.  I think of it as you living your life in an accelerated time frame during your travels - but when you get into combat, time goes back to its slow old self and everything appears halted.  In reality, you would be regenerating just as _fast_, or a curse might be taking your life just as quickly but in combat it would essentially be zero.

I don't like 100% regen after regular combat.  Perhaps after dungeon bosses or other major fights there will be some manner of health bonus as a reward, just as there is xp.

**Comment by malikoth** [comment]
That's a good perspective on regen, Josh, I like it.  Although things like
skirting a boss's lair happens in that "accelerated" overworld mode when
it's really more something you'd do on the combat time-scale, I think that
explanation really makes sense to me in general.

**Comment by basepi** [comment]
I'm not big on the accelerated time thing, though that's more how the mechanics will work, I think.  But like @Jzar said, we have actions we do in the overworld that represent the same time scale as in combat, so explicitly making the overworld "faster" I think would be an encumbrance rather than an advantage.

I'm ambivalent as to whether we give 100% XP after battle.

**Comment by BlackVegetable** [comment]
Did you mean 100% HP @basepi ?  Regardless, I think the accelerated time is a mindset we'll have while developing but not something we'll force as a mechanic in every possible way, nor something that we should announce to the player.  

We still need to decide if we are healed after combat, and if we are healed over time in the main world.  If we do not have automatic healing after combat, individual fights need to become easier.  This is because fighting one group of monsters and then fighting another nearby group shortly afterward will become very difficult if you enter in with 25% hp at the start.  

If we heal fully after fights we can make the individual battles harder.  Also, we avoid the issue of running away from a nearly dead monster and casting healing spells until the party is fully healed before finishing it off so you will have 100% hp in the overworld.

**Comment by basepi** [comment]
Yes, I did.

With the points you've made, I vote 100% HP after battle, no regen in the overworld.

But I'm fine with either system.

**Comment by malikoth** [comment]
Alright, I'm sold on it.  100% HP after battle, no overworld regen.  Josh, I know you objected to this mechanic, but remember that health regen post-combat was suggested in the first place on the assumption that if we had potions and whatnot, the user would sit down and heal up to full after every fight anyways.  So this mechanic just cuts out content (waiting, which isn't really content) that nobody likes anyways.
