### ISSUE TITLE
Respeccing

### ISSUE THREAD

**Issue by malikoth** [akintu/akintu#11]
(Sorry guys, wall of text crits you for 9000...)

So, here's the issue: Devin hates D3's ability to change your abilities at any time with virtually no cost, and I have always hated how strict some RPGs are (D2) on character build, once you've made a decision.

After talking around it a little bit, we realized that this was the issue causing us to approach certain ideas and decisions so differently.  Devin suggested simply making the ability to change your character choices an option.  We decided that this is something that you should probably be able to select at character creation, right next to the option for hardcore mode.  Even if a mutable character is playing on the same server with immutable friends, he'd still be able to change his choices.

We liked that this gives the choice of how hardcore the game is to the player himself.  However, I've been thinking about how the game changes as you transition from single to multiplayer mode in Akintu.  

So you've got your character, and you can play it in your own world on your own computer.  If you want to play with a bud, you can invite him to your world, or he can invite you to his, but your character data still comes from your computer.  (Correct me if this isn't how you envision multiplay working!)  Since one player has no control over his friends class choices, we may end up with a ton of players choosing one primary class.  And they may all be melee characters, which would probably make team play pretty boring, and hard to work your way in to weapon range without getting your skull cleaved by your berserker buddy's backhand.

Basically, I'm thinking that even with a variety of secondary classes, it will be good for multiplayer play if people can adjust their classes.  Even the ones that want to play the strictest version of the game.

So one possible solution would be to have dual-spec like in WoW.  You can hit the toggle button, and go from fighter / thief to fighter / ranger, and back again.  Your choices made in each spec are remembered anytime you are in that spec.  It still requires you to plan your build ahead of time, but gives you a little bit of flexibility at least.  Mutable characters however, would be able to switch between any of their 3 (or 4) secondary classes) any time out of combat (or maybe just any time in town) and be able to adjust previous character choices too.

Or we could not limit the number of specializations.  Have one for each secondary class.  Let any player switch their secondary class sometimes (out of combat, or else in town).  Have the difference between mutable and immutable characters simply be that immutable ones cannot change previous choices made in each secondary class spec.

Sorry, this is far more rambling than I wanted it to be.  Hope some of it makes sense.  Let me know how you guys feel.  Like one of my ideas?  Have alternatives?  Think it's a non-issue and we should stick with one spec?

**Comment by BlackVegetable** [comment]
I think having a team that happens to be all fighter/ranger (dragoons) should _feel_ a certain way.  That is, it would be a particular challenge for that team to progress some of the time, and perhaps certain obstacles would be extremely easy to overcome.  That feel shouldn't be seen as a bad thing.  Part of the fun of creating a particular party combination is seeing how well you can do, not simply tweaking your group until you have the "optimal" build before continuing.  This won't be a competitive game, so there shouldn't be an issue with non-optimal parties feeling pressured to play differently.

Additionally because each Dragoon very likely made his own passive and secondary choices differently than any other of his Dragoon buddies, there will still be some difference.

Finally, this game should be fun enough that players will not feel terrible about creating alternate characters dedicated to just playing with a single group of friends.

**Comment by BlackVegetable** [comment]
Oh yeah, lets get the other two notified: @basepi @jabelch

**Comment by basepi** [comment]
FYI, I get notified for everything, since it's my repo.  =)  But still mention me, just for completeness.

I like the idea of an Ironman (term from X-COM, we can name it differently) mode where decisions are permanent (You can't make individual save files in Ironman in X-COM, and it autosaves after every action.  Thus you are stuck with your decisions.  However, I don't think the Ironman setting should change just because you enter multiplayer.  Create another toon if you want the flexibility.  It takes away from the "prestige" of Ironman if all you have to do is enter a multiplayer game to respec.

I do have strong feelings that respeccing should be only possible in town.  I don't want D3.

**Comment by jabelch** [comment]
I agree about respeccing in town.  I just posted this idea - perhaps even in ironman mode you want to change - we make it so costly that it is only done out of desperation.  Perhaps the cost is in gold or in stats/attributes/level xp...
Maybe all changes should have some form of cost chosen based on the gameplay the user chooses.

I also like the idea that switching between classes "remembers" where you were last. You maybe gained xp picking a lock as a thief, but now as a wizard you must relearn it as a spell.  As a wizard your intellect enabled excellent identification of curses, but things get hazy in your puny brain as a fighter.

I also agree that your decision should not magically change when you want to play multiplayer - UNLESS the experience gained as multiplayer is limited there. - I'm not as much of a fan of this idea though.

**Comment by malikoth** [comment]
Thanks for your feedback and ideas.  As you could probably tell, I was
really conflicted on the issue.  I like the term Ironman, and Colton and
Devin have convinced me that that's probably the best way to do it, is just
true Ironman.  Though if you like Josh's idea, we could still say "You can
switch secondary classes if you give up 5 levels to spend time retraining"
or something obscene like that.

For those of us who will never EVER play on hardcore or Ironman modes, I do
however like the idea of storing character setup per secondary class.  Just
remember that it's your secondary class you can switch, not the primary
class.  If you're a ranger, maybe your pa was a fighter and you were the
paige to an arcanist when you were 12, and ran with the local thieves guild
when you were 16.  So you've got a little of each of the other classes in
you, and you're just calling on one of those three to support you and give
your primary combat style a bit of a flair.  Changing secondaries doesn't
actually change anything about you, just how you think about fighting and
your style.

On that note though, Devin's added a list of (small) stat bonuses
associated with each secondary class, and I do really like that system.  It
makes sense to me that if your current secondary is wizard, that the act of
casting the occasional spell here and there temporarily boosts your
intellect.  Not so much that you wouldn't lose that intellectual edge if
you decided you were going to whip out your Buster sword and start mauling
things when they get into melee range instead.

And I had been thinking that while only wizards can cast spells, anyone can
try to pick a lock.  You just won't have very much success since you don't
prioritize cunning as a wizard.

**Comment by jabelch** [comment]
That does make a bit more sense.  I like it.

**Comment by basepi** [comment]
The idea behind Ironman is that everything is permanent.  You have to create a new character to change your choices.  Making it possible to change your choices even for an obscene price means we probably just should not do Ironman.  I don't know, that's how I feel.  That's like saying Hardcore means "you lose the last 10 levels if you die" instead of "death is permanent."  Maybe I'm being stubborn, dunno.  =)

I'm fine with keeping secondary profession progress.  Though if progress is tied to levels, I think we're already going to be doing that.  You switch to your secondary, and you have all the abilities up through your current level.  I don't really like the idea of having primary and secondary levels that can be different.  =\  Then I feel like I have to grind each secondary.  Though maybe that's still a good way to go.

**Comment by BlackVegetable** [comment]
Old-school gamers that select ironman will want no option to respec at all.  (I spoke with such a player recently who was surprised we would even bother to allow respeccing as an option.)  Plus it adds a little more work for us without much benefit.

Can someone clarify if the secondary progress is something that you swap and need to reset all of your ability points associated with it, if it means you reset just your secondary abilities, or if it means something else?  I'm now confused.

**Comment by malikoth** [comment]
Let's settle then on Ironman being absolutely set.

I don't know for sure all the abilities and points and whatnot that make up our characters yet, so I don't know exactly what switching secondaries really entails.  However, I had been thinking only of abilities.  Say if you set one ability to a hotkey, but that ability is no longer on your list when you switch to another secondary, it should go back to your hotkeys when you go back to your first secondary.

Clear as mud?

**Comment by BlackVegetable** [comment]
Alright.  You shouldn't have access to passive abilities unique to a secondary class after switching to another.  I think you'll have to select those on switching each time.

**Comment by basepi** [comment]
Oh, for sure, I don't think anyone was suggesting you keep abilities from other secondaries...that would be...silly.  ;-)

As far as keeping your hotkeys, tier 3 feature.
