### ISSUE TITLE
Seed-based treasure chest content?

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#126]
Do we want treasure chests to always generate content based on the world seed?  Or may it vary from different instances of playing the game with the same seed?  I know it will be easier for me if it is allowed to vary, but I think the world seed won't be nearly as interesting unless it impacts items/treasure chests.

Thoughts @jabelch , @Jzar  (and maybe even hear from) @basepi ?

**Comment by malikoth** [comment]
I vote completely random.  I think the seed should affect the layout of the world itself, but that once the world has been created, it be allowed to follow its own non-deterministic path through space-time.

**Comment by basepi** [comment]
I'm with @Jzar.  I think the most interesting part of world generation is having the same world layout, not the same items.  Right now, that's not as obvious because our worlds are SO random, there's nothing particularly "cool" about a specific seed.  In fact, I think monsters could even be unhooked from the world seed if we wanted, for the same reasons.

**Comment by BlackVegetable** [comment]
Fair enough.  That's less work for me.  Hopefully we get really REALLY cool stamps going.
