### ISSUE TITLE
Hidden Objects (and Monsters?)

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#15]
I have a couple of questions that can be seen on the https://github.com/basepi/akintu/wiki/Awareness page.  

They are regarding the distance from which we should be able to attempt to detect hidden objects and whether we should try to include monsters that can stealth (and should they do so on the overworld?)

**Comment by BlackVegetable** [comment]
@basepi @jabelch @Jzar

**Comment by malikoth** [comment]
In Moria, the awareness roll for hidden objects is made every single turn.  Every time you move, you had a chance of discovering hidden items within the range of your awareness (which is simply the range of your vision, I believe)  If your awareness wasn't up to par, but you knew for instance that there had to be a door nearby hidden somewhere, you could put yourself near where you knew the door to be and press S a couple, or a hundred times and each button press you'd roll again to see if you can find it yet.

Although I'm not really very invested in this decision, it seems strange to only allow a single roll ever to discover a hidden item.  That seems like saying there's a bug in your program, and if you can't find it in one re-compile, then you never will.  Well, that's obviously false; particularly if you know it's there, and you're looking for it, you will find it eventually (and presumably fix it).  Even if you don't know it's there, you may yet discover it by chance when you're looking over the relevant code later on.

So it seems to me that we should be a little more forgiving regarding chance to discover things, but like I said, I'm not really particularly concerned with this decision.  The system you have and the scale you've set up seems fine to me.

As I mentioned, the range for detection in Moria I believe is simply the range at which you can see objects.  We could copy that, or perhaps calculate the distance from the object, calculate the percentage of your total vision range that it's at, and then scale your cunning for that roll accordingly.  With this idea, you'd have a better chance to discover the closer you are, but the cap is still whatever your cunning is.  To get the full effect of your cunning, you'd have to be right next to it.  If you wanted to use this, I'd probably scale back the difficulty of discovering them a bit I think, since the majority of the time, you wouldn't even get to use your full cunning value for detection.

And yes, I would vote for invisible monsters too.  Moria has lots of invisible (aka stealthed) monsters.

**Comment by BlackVegetable** [comment]
The one roll ever idea was borrowed from Neverwinter Nights.  I'm not tied to it though.

I think the range of vision would be easiest to implement and makes sense.

Let's allow searching every move as well, I'll just adjust the range of possible values in the rolls from 75~100% to 50~100%.  Don't worry about calculating distance and adjusting Cunning; if we find it is too easy to find stuff, we can raise the required levels a bit.

**Comment by malikoth** [comment]
Sounds reasonable, I like it.  I wasn't sure how tied to that idea you
were, which is why I was suggesting some slightly more complicated ideas.
I like the thought of keeping it simple though.

**Comment by basepi** [comment]
I think invisibility on a monster should take a pretty high percentage of their "difficulty" rating.  Seems like that's a pretty powerful ability on an enemy.  But I dunno, I've never balanced a game before.....

**Comment by basepi** [comment]
Also, everything else you guys have said sounds fine.  Don't care on this one.

**Comment by malikoth** [comment]
Sounds settled.  Closing.
