### ISSUE TITLE
tile_is_open crash

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#163]
I can't seem to grab my stack-trace but it died at line 252 in server.py in tile_is_open which was called from line 29 in ai.py in wander...  I was a couple of panes away from the starting location.

**Comment by malikoth** [comment]
I need stack traces.  Right click your console, select Mark, select everything that appears relevent, then press Enter to copy to clipboard.  Then paste here.

**Comment by malikoth** [comment]
I also need a lot more details about the exact state of the game (in combat, in overworld, pane #, etc.), what you were doing, basically I need to know how to duplicate it.  I literally can do nothing to try to solve this, because even knowing the line number that failed, I have no way to identify why.  That line works fine the majority of the time.

**Comment by BlackVegetable** [comment]
It's possible that by fixing the other bugs, you've managed to fix this one as well.

**Comment by BlackVegetable** [comment]
I'm going to close this for now.  If I encounter it again, I'll reopen it and hopefully provide more details.
