### ISSUE TITLE
Move a class to Medium Armor Tolerance

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#181]
Anyone's input is welcome, but I think @Jzar is most likely to care about this.  

We only have two classes with Medium Armor tolerance: The Battle Mage and the Anarchist.  While some other classes may find it preferable to use medium armor some of the time I think we need one fewer light armor user and bump it up to medium.  

The classes I am considering for this are:

Marksman (Leaning toward): Heavy ranged damage dealer with excellent accuracy.

Druid: Hybrid ranged/melee attacker with powerful poison bonuses and a strong poison trap.

Tactician: Hybrid ranged attacker/caster with buffing traps and an anti-caster focus.  

When I get around to it, I think the tactician will need the buff the most, but it doesn't make a ton of sense to me given he is half-wizard.  The Druid might need a little help, especially to give a viable melee option to it.  The marksman won't be in melee when he can avoid it, but thematically makes more sense than the others.

Thoughts?

**Comment by malikoth** [comment]
At this point, I may be the most likely to care, but I just don't care.  Do whatever seems best to you.

However, as long as you're asking for input, I'd vote moving both the druid and the tactician to medium.  Ranged characters tend to need less armor, so that's why I exclude the marksman.

I say convert Tactician simply because you say he needs a buff.  Thematically, I have no problem with that.  It's kind of a stereotype that casters have to wear cloth because I guess they want them to be portrayed as physically weak, and possibly also because the very nature of magic makes that character potent already.  But if you play the Elder Scrolls games, you can create an incredibly powerful mage ... and by simply wearing and using plate armor all game long, that's what he'll build skill in, and then he'll be a perfectly functional plate-wearing caster.  I've uh, done that, uh, several times.  In fact, that's why the Spellsword and Battlemage are some of the classes I'm more excited about in Akintu.  Having more armor doesn't detract from the game experience.

I also say convert the Druid because he's in melee, and melee characters tend to need more armor.

**Comment by BlackVegetable** [comment]
Fair enough.  I'll make the changes after the Beta demo.  (The changes on the wiki will only be on the public repo.)  Giving the Tactician medium armor may help him get close to melee allies and lay down buffing tiles ("Favors") that otherwise he might be hesitant to move into range to use.

**Comment by BlackVegetable** [comment]
Updated on the public wiki and the data files.
