### ISSUE TITLE
Combat completion breaks if battle is on pane edge

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#182]
If you enter (and finish) combat that happens the moment you change panes, the game will crash (every time I believe) upon completion of the battle.  victory_phase line 354: NoneType has no attribute 'id' (servercombat.py)

**Comment by malikoth** [comment]
I can't duplicate this.  With key 'fdsa', I'm moving to column 6 (Just on the left side of the left house touching the house), and then moving off the bottom of the pane into the next one.  A monster spawns right there, and after both defeating all monsters, and letting them kill me off, I respawned as expected.  I can't say for sure, but I think the thing we fixed with making combat end immediately upon killing the last monster might actually have fixed this.  Therefore, I'm going to close it.  Reopen if you can still duplicate this error, and tell me the key you're using and exactly where to go to cause it.

**Comment by malikoth** [comment]
And just as a note, since I may change a module's code between when you post a bug report and when I can look at it, line 354 may no longer be the line number where the error is.  The stack trace also includes the actual code on that line, and it would really help me out if you could at least post that as well, even if you can't always mark up the console and copy text out of it.
