### ISSUE TITLE
Need to call update_person() more often for other players

### ISSUE THREAD

**Issue by basepi** [akintu/akintu#196]
For example, when someone else levels up, it won't update their level on your screen until you switch panes (their person is re-added to your gamescreen)

**Comment by malikoth** [comment]
I'm not sure the updated person details are even being sent to the other players in the pane.  I'll work on it.

**Comment by BlackVegetable** [comment]
It also needs to be called more for the active player.  I mistakenly submitted a commit that mentions that you have been assigned an issue to resolve HP/MP/AP inaccuracies to the single-player as well.  This isn't the case, turns out.  I'll make a separate issue about that part and assign it to myself.

**Comment by malikoth** [comment]
Levelup actions now broadcast to all relevant players.  If there are other specific instances where a value is changed but not displayed, please reopen this issue and describe the situation in as much detail as possible.
