### ISSUE TITLE
Detecting Hostile traps in combat

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#214]
I need the functionality to place hostile traps on "random" tiles at the start of a combat pane's generation.  That is, I need to have traps placed on tiles that are passable AND are not within 1 tile of where a player could enter combat from.

I will place the traps there myself, but I'll need a method to generate a list or set of those tiles/locations after everything else has been placed (aside from perhaps, the player.)

I'm assigning this to Kyle but I feel that @jabelch may need to be involved...

I'll take over once that set or list generating method is completed.

**Comment by malikoth** [comment]
I really think this belongs to @jabelch.

**Comment by jabelch** [comment]
Done and pushed.  See pane.py, method CombatPane.place_traps(number) (approx line 539)

Right now I am passing in the number of players (that we use for monster HP boost) and adding 3 times that number of traps.  I'm not adding the traps yet, since you said you'll do that.

See self.traps_region as a set of location objects that are valid options.

**Comment by BlackVegetable** [comment]
Excellent.  I'll take it from here. If we want to have a special image for enemy traps (or one for each enemy trap) you could hunt for those.  Crap, why did I close that other issue?  I'll reopen it.

**Comment by BlackVegetable** [comment]
The images for traps is a separate issue.  The next piece of this progress is getting them to be displayed and detected.  I can handle the detection part.  @Jzar, what did you do to make the traps visible before?

**Comment by BlackVegetable** [comment]
Done.
