### ISSUE TITLE
Cannot move after having very low AP and pane switching

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#216]
If you equip a bunch of gear beyond your capacity, and then switch panes, if you are overburdened enough, you will not be able to move.  This persists even after dropping (destroying) a bunch of your gear.  Pressing F2 to open the shop and then closing with SPACE will allow movement again, but why is this happening in the first place?

**Comment by BlackVegetable** [comment]
I've _fixed_ this to the point where it is immediately evident at any point after overburdening yourself.  A related remaining bug is that we have a display issue.  When your AP reaches the point where you cannot move any longer, your current AP stops updating.

**Comment by malikoth** [comment]
I'm pretty sure you need to fix this, as this happens even without paneswitching.  Let me discuss briefly what my tests have shown me:

Sometimes, the ITEM CREATE command handler in game.py is told that person.AP and person.totalAP are both 1.  At this point, you cannot move anymore.  From here, I believe there are two issues:

First, when you go to the shop and close it with space, it's creating a whole new Person object for you, and I believe there may be some non-deterministic elements in the (re)hydration methods, which is why when the new you comes out of the shop, you may have 5 totalAP instead of 1 (if your encumberance wasn't too high).

Second, AP is not being adjust along with totalAP.  So when you start deleting things, you can still be at 1 AP and 20 totalAP.  I'm not sure exactly what event it was that finally triggered the refresh to get me back to 20 AP, but it did finally jump back up.

I believe the first course of action for you would be to make inventory adjustments adjust your AP value directly.  For instance, inventory.py line 100 that says "# Check for weight here?"  I think that would a great place to check for weight, and adjust AP values.  Same goes for removeItem  This will also make it so that the line in game.py that reads "'AP' : self.pane.person[self.id].totalAP}) # This is an intentional mismatch." should no longer be referencing totalAP, as AP would finally be reflecting current values.

**Comment by malikoth** [comment]
I'm not sure what to do if I'm correct about the non-determinism of creating the new PlayerCharacter object.  Instead of passing around that whole object however, I might suggest instead issuing individual inventory commands like CREATE, DROP, EQUIP, REMOVE, and then just having both the server and the client adjust that player's inventory accordingly.

**Comment by BlackVegetable** [comment]
I don't think you are correct about the non-determinism.  But otherwise I'll look into the things you mentioned.

**Comment by BlackVegetable** [comment]
One "bug" is that you should be able to move in the overworld even if you have 1 AP.  I don't know where this check is happening to not allow movement then.  What we need is a UI indicator or other clue to tell the player to destroy gear or sell it to a shop, or else they will be totally vulnerable in combat.  Being set to 1 AP is intentional.  However, I'm looking into the incorrect AP values being set even after trashing stuff.  I think it was just an old, desperate implementation that was sticking around that I have to reverse.

**Comment by BlackVegetable** [comment]
This bug was the result of a typo... UDPATE instead of UPDATE.

Bleh.  (The not moving part is still a mystery to me, but it kinda makes sense as is...)
