### ISSUE TITLE
Game fails when save-return followed by save-exit

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#246]
I'm not sure if I should've assigned this to @Jzar instead.

If the game saves and returns to normal gameplay, something fails because subsequent calls to save_and_quit will cause the game to crash (and I imagine, not save.)  It gets a keyerror.  

This can very easily be reproduced.  To access the save menu, use CTRL+q or CTRL+x.  To "Force quit" use CTRL+SHIFT+x or CTRL+SHIFT+q.

**Comment by malikoth** [comment]
Is it saving just the current character, or trying to save off the whole world?  If it's trying to save the world, I'm not surprised, because that process was designed to happen when you exit, and destroys the world in the process of saving it.

If it's just trying to save the player's character, then I don't know what's going on and jabelch will probably have to fix it.

**Comment by jabelch** [comment]
Currently getting a "global name 'screen' not defined" error on line 522 of game.py.

**Comment by BlackVegetable** [comment]
That part has been fixed, back to you Josh.

**Comment by jabelch** [comment]
Kyle, you are correct.  The game world is being saved on a save and continue.  It is handled in game.py line 455 save_no_quit() which calls gameserver.save_all(), which calls self.unload_panes(unloadAll=True).

Since saving panes requires the list of persons to be placed back in the pane before saving, keeping the for loop on line340 of server.py is necessary, but perhaps we can add a third parameter to unload_panes indicating that we don't want to shut down the ai, but we need to run that loop still.

If you give me your blessing, I can go ahead with it.  Otherwise, is this something you can handle?

**Comment by malikoth** [comment]
Josh, you're welcome to take care of that.  I trust you with this code.  :)  However, the fact that it shuts the AI down, and indeed the fact that AIs can be started up and shut down, is there because I was experiencing errors with trying to operations with live AI behaviors running.  I don't recall exactly the nature of the errors, or what it might take to work around them.  So just know that it may not be as straightforward as it seems.  I'm just not sure.

If you don't want to deal with it, leave it on my plate, and I'll try to finish it up in the next two days.

**Comment by jabelch** [comment]
Fixed.  Note: I'm not shutting down the AI behaviors before saving, but my tests seem to work.
