### ISSUE TITLE
Help Menu UI

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#252]
We need a UI page to display a wall of scrollable (vertically) text and have some cues as to which buttons to press to navigate via scrolling as well as BACK, TOP, and EXIT.

**Comment by BlackVegetable** [comment]
The pages are in text files.  Will you be able to read in a big 'ole string from them?

**Comment by basepi** [comment]
Wait, it will not be scrollable.  I planned on making it multi-column,
because it didn't look like you'd have anything too long.  But scrollable
is quite a bit more work.  Did you end up with really long help pages?

I only planned on the keys for BACK and EXIT.

I could definitely read from the text files -- but I figured to make it
more generic it would make more sense for you to read from them and then
pass them in.  _shrugs_

**Comment by BlackVegetable** [comment]
I'll pass them in.  Give me a NEXT button then.

**Comment by basepi** [comment]
KK.  Just curious, which help files ended up really long?  The ones you originally showed me were very reasonable.

**Comment by BlackVegetable** [comment]
How to play ones are pretty long.  The ones I've done are all pushed.  You can check your folder and look at the largest file on you system.

**Comment by basepi** [comment]
Done.  Feel free to open an issue or ping me on IRC if you want changes made.
