### ISSUE TITLE
Beta Testing Hype

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#26]
I've been thinking about what Josh suggested regarding making the wiki open to the public in order to increase the interest in our project.  

I wonder if there is a way we could make a copy of the wiki, edit that wiki to remove some development only details, and make the wiki viewable by everyone but editable by only us.  If we could do this, we could show it off to people in order to make them want to Beta test our game.  I think we will want lots of beta testing as early as 7-8 weeks into next semester.  Otherwise, there is no way I'll be able to fully balance the content enough to implement 20 levels.  (I _am_ taking one other class after all!)

Josh also suggested we make one of those square barcodes for phones to link to this wiki. (What are those called again?)  We could have it link to _that_ wiki and have it available on cards that we pass out during our next presentation.

Finally, I wonder if it would be a good idea to have a simple website set up to sign up for beta testing such that people enter in contact information for themselves, and what classes they are most likely to test.  That way we can easily contact interested people as soon as we are ready AND we can know which classes _we_ need to test more.  Furthermore, by doing it this way, we could limit the maximum number of beta testers if we wanted to do that for some reason.

What do you guys think?  Is this doable, and if so, is it desirable?

@jabelch @Jzar @basepi

**Comment by malikoth** [comment]
I don't know if we have that much granularity of control over what parts of our project are public or private.  I thought a repository (and associated tools like issues and wiki) are all either public or private together.  Colton will correct me if I'm wrong.

In addition to that, I think balance testing should be one of lowest priorities.  I mean, right now in design phase, I think we should strive to create systems that seem inherently balanced because that will help us make it fun.  But next semester, I think the vast majority of our efforts should be in developing features and making the product look good, rather than ensuring all of the abilities scale well through all the levels.  Since we'll only get to show a tiny percentage of what our game does, I'll be a lot more concerned with how well it works and what it looks like.

I do support beta testing, and we've got a pretty interested audience in our class.  I've even had a few friends who I've told about our project express interest in play-testing.  So I'd love to have a website with periodic snapshots of the project, so we can point our interested classmates there, have them download it, and give feedback.  But I wouldn't feel the need to involve the general public just yet.

As alternative to creating a separate website for this, we could just make the repo public and tell people to use the issue tracker intelligently (is that too unreasonable to expect of general public?).  Colton, do you have to have a Github account to see and give feedback on public repos?  Honestly, none of this stuff is trade secret, we don't need to obscure it from other people's view really, and I don't see a problem with letting them be able to download older builds either.

**Comment by BlackVegetable** [comment]
They wouldn't be able to edit stuff willy-nilly would they?  Also, I was wondering if there was some process to copy the wiki wholesale to some other form of wiki, but that sounds like a long-shot now that I think of it.

**Comment by BlackVegetable** [comment]
I think we'll address making a wiki public when we're close to release.  The rest of this has been resolved.

**Comment by basepi** [comment]
Just FYI, the wiki is just another git repo.  We could pull it down, and then push it to a public github project super easy.

So if we want the wiki to be public, it should be easy to do so.

**Comment by BlackVegetable** [comment]
Neat, we'll worry about that in a few weeks.
