### ISSUE TITLE
Stop being so awesome

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#275]
Seriously, you're making the rest of us look bad.  This applies to a lesser extent to @basepi and @jabelch.

**Comment by basepi** [comment]
I think @BlackVegetable should actually be assigned to this one. Or maybe all of you guys. =)

**Comment by malikoth** [comment]
Working as designed.  Not a bug.  Won't fix.  Closing issue.

**Comment by malikoth** [comment]
lol  Seriously, I joined the team because of you guys, and no other reason.  I was not let down, you all have been a dream to work with.  I loved working jointly with both jabelch and blackvegetable, and was sad I never got to sit down and pair program with basepi.  You guys all came through for me when I wanted to implement something, but I'd reached the edge of my expertise, each of you stepped in and said, "Well sure, I can do that for you" and we'd finish something up.  It's just been a wonderful experience, and you're all awesome!

**Comment by basepi** [comment]
Amen!  And once I get up to date on some of the game and server code, we can work on it together in the future!  =D

It's been fun, gentlemen, and a pleasure to work with you.  =)
