### ISSUE TITLE
Performance Slowdown

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#292]
I think we all know what I'm talking about.

Locate the slow down and reassign to someone who can handle it.

**Comment by BlackVegetable** [comment]
Found the offending commit.  It belongs to @Jzar !

https://github.com/basepi/akintu/commit/a8cec5d093294e55629ff78f15aec2177adba75f

Fix it!

**Comment by basepi** [comment]
My bet is that it's related to calculating a bunch of regions all the time, but I only did a quick glance over that commit.

**Comment by BlackVegetable** [comment]
Kyle fixed it.

**Comment by malikoth** [comment]
Close.  I was creating a single region multiple panes wide.  One corner of the region was in pane (0, 0) and the other was in whatever pane the player was in.  So the size of the region was increasing _really fast_ as you moved panes further and further from (0, 0).  I moved the corner from (0, 0) to the player's pane in the initial commit that caused this bug, and the fix was to move the other corner of the region also from (0, 0) to the player's pane.

**Comment by basepi** [comment]
Is this region still necessary?  Seems odd.

Not that it's slow anymore, just curious.
