### ISSUE TITLE
Threat and AI

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#37]
Hey, what are you guys thinking as far as the mechanics for determining which party member gets attacked?  There are various strategies to implement this, none of which I support at the moment.  I'd like to throw ideas out there and have you guys tell me what you think.
- Totally random (whatever they can reach)
- "Threat" built from damage/healing sources (a la Wow)
- Heavily armored targets build more threat than lighter ones (a la Dragon Age)
- Wherever damage can be maximized (a la Fire Emblem)
- Hates certain classes more than others
- Any suggestions?

@basepi @Jzar

**Comment by malikoth** [comment]
I've always though "If I were boss X in WoW, who would I aggro on?  Who would I kill first?" And the clear answer is the healer.  After I've destroyed a raid's survivability by killing off all its healers, I would go for the DPS next so that the raid can't hurt me anymore.  Then, when they're the only ones left standing, I would get around to killing off the dumb tanks.

Basically, that aggro system seems completely non-sensical and contrived to me.  In further thinking about how you could make a tank into the player that actually is the most threatening to a boss, he'd have to be applying some form of CC to the boss.  Then when the boss (correctly) decides that the healers are the easiest targets and the most important to the raid, he'll go towards them, and the tank will knock him back, or slow him down, or taunt him (for a small duration), or snare or stun, etc.  Boss will never be able to reach the healer (who is also kiting the CCd boss), and will then get frustrated and have no choice but to turn on the tank and try to kill him so he can get to the squishies.

Originally, I was thinking that we could denote tanks by giving them CC abilities with higher than average availability and reliability.  But that would be hard to balance with our already difficult combination-based class system.  So we could just give everyone whatever CC they would already get, and let it be accepted that you need some mitigation and/or avoidance if you want to dance the dance in melee range.  Then the rangers and wizards can apply what CC they have too, kite when appropriate, and force the monster to attack the melee chars.  Melee in turn, will be built around having a little more armor, some dodge etc., so that they can take this.

**Comment by BlackVegetable** [comment]
I'm not sure what solution you proposed... (did you propose something?)  How will we set the AI to determine who to attack?  Furthermore, any Wizard character (we're talking 7 classes) are capable of being healers.

**Comment by malikoth** [comment]
AI will attempt to attack anyone who has recently cast a healing spell, or if there is no such character, whoever's doing the most damage.  If that character is at range, the monster will attempt to go towards that character.  However, if it wastes 2 or 3 turns trying to damage that character but can't due to CC, it will give up and pick a target within melee range that's doing the most damage.

**Comment by BlackVegetable** [comment]
Perhaps we can have several personalities that we program and assign a personality to each monster we create.  This strategy might be "vindictive" or something.  Another might be "dumb" or "hungry" that just attacks whatever is closest.  We could come up with 4 or 5 personalities and have certain monsters behave differently.  What are your thoughts on that?

**Comment by basepi** [comment]
I'm thinking this level of AI should be a level 3 feature.  I think for demo day, if the mosters just go for the closest guy, it will be good enough.  Just a thought.

**Comment by BlackVegetable** [comment]
That's fine.  We could set that up as a default behavior that is overridden if another AI strategy is supplied.  I suspect I may have unrealistic expectations for what we can accomplish in our semester...
