### ISSUE TITLE
Monster Groups/Numbers

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#39]
This will probably require more than just a text discussion but we can at least put down some starting ideas here.  

I have balanced several of the classes around there being more than one monster to encounter at a time some/much of the time.  This especially becomes important as we have multiple players fighting as a team.  

I have a baseline proposal for handling multiplayer balance vs. monsters.  I'm not set on it, but it is something to start from:
- Some monsters have a tendency to be in groups.  If a player is alone in his region, he will only face a few of them at once (maybe just one.)  If he has friends in the region, the number of monsters is increased, but HP remains constant.  If players suddenly join the region from far away and then join the battle, either additional monsters can enter as well, or their HP can be multiplied.
- Some monsters have a tendency to be alone.  If a player is alone in his region, he will face them with default HP.  If he has friends nearby, he will face it with HP proportional to the number of players.  If players join from far away (or connect to the game right then and join the battle) the monster's HP is multiplied.
- Other monsters fall somewhere in the middle.

Thus, a monster on the screen may indicate a group of monsters of that type (or of similar types including that type) or just one monster of that type if it is a loner kind of monster.

Ideas? @basepi @Jzar

**Comment by malikoth** [comment]
First off, I don't think any numbers should ever be changed in combat.  If that means the way you think is fun to play is constantly disconnecting and reconnecting to join into fights, fine, whatever.

I like the idea of having fights scale both health and enemy quantity.  I think that if the number of monsters scales with the number of players nearby (within 2 screens, matching Colton's suggestion for shared party XP), their health should also scale slightly (1.25x?) to offset the additional power of player synergy.  Especially since I don't think we'll be giving the monsters terribly great synergy.

By the same note, I think monsters that just scale their health with the number of players present should scale it more than proportionately with the number of players.  2p = 2.5x, 3p = 4x, 4p = 6x maybe.  Same reasoning.  We get synergy.

All of these numbers by the way, I think we shouldn't worry about them, just let me be anything.  When we have a working game we can playtest with, then we will get a sense for if monsters are dying too quickly or too slowly, and adjust from there.

**Comment by BlackVegetable** [comment]
Fair enough, I like your idea of allowing for disconnecting playstyles.  I forgot that we weren't having to babysit our players in this game.

**Comment by BlackVegetable** [comment]
I think we've settled this one.
