### ISSUE TITLE
Out of combat buffs

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#6]
How should buffing spells out of combat be handled? Can wizards enter combat with all of their most powerful buffs already in place? Is there an out of combat real time limit for each buff? Is there a hard cap on how many buffs a player may enter combat with?

Colton: For simplicity and balance, I think there should be no out-of-combat buffs. Perhaps we make the buffs a little stronger since they have to use action points to cast them at the beginning of battle?

@jabelch

**Comment by jabelch** [comment]
I don't like the idea of being able to cast spells _just_ before combat.  I mentioned in another post the idea that combat and shops would be more of a real time thing while walking around and such would be more of an accelerated time perspective.  That way, the player appears to have no health regen during combat but it exists otherwise.

The same concept could apply here.  If a player wants to apply buffs outside of combat, great! But they would essentially run out almost instantly.  It is helpful for perhaps health increases, but outside of that it would be pointless.  So in that sense, maybe having the option is pointless since doing it on accident would be frustrating and counterproductive for our game.

**Comment by basepi** [comment]
Ya, I think we just don't have them out of combat -- having them expire immediately just adds complexity and frustration to the user.

**Comment by BlackVegetable** [comment]
@Jzar needs to put in his 2 cents and then we may consider this closed.

**Comment by malikoth** [comment]
I agree, no spells out of combat.  Case closed.
