### ISSUE TITLE
Tile Image

### ISSUE THREAD

**Issue by jabelch** [akintu/akintu#60]
Currently Tile keeps the path to it's background image, but it would be useful to keep the actual image data.  That way we don't have to save each individual image to disk.

**Comment by basepi** [comment]
I thought about it, and I think this is not what we want to do.  Because then we store 15 million copies of a given tile.  If we never reuse a tile (unlikely) then it might work, but otherwise I was just hashing the filename and only loading the image if it hasn't been loaded previously.  It will save us a lot of memory and a lot of loading time to keep it with just the filename, and only load if needed.

**Comment by basepi** [comment]
And again, I don't know that we should generate the tiles on the fly.  Causes a lot of overhead in the client, where we're already going to want to be as quick as possible.  Lots of sprite files will be fine.

Additionally, I'm still not completely convinced we should use large files and split them up.  This makes it really hard to see the tile pattern without drawing actual tile lines.  We could draw these lines if we wanted, but I'm thinking choosing a few tiles and then re-using them will solve the problem and still be at least a _little_ subtle.  We want to be able to see the boundaries so people can count tiles for ranged spells and whatnot.

You should probably join this conversation, @Jzar and @BlackVegetable, I wonder what you think.

**Comment by basepi** [comment]
Also, having the image split up like that makes it too high-fidelity, in my opinion.  all of our sprites are going to be fairly pixelated, and then the background is super detailed?  I dunno, just brainstorming.

And rambling, from how much I've already written.  Maybe we should just talk about this on Saturday.

**Comment by BlackVegetable** [comment]
What do you mean by "on the fly"?  Are you arguing for or against saving them to disk?

**Comment by jabelch** [comment]
I want to play around with putting overlays on these images so that it makes it less realistic.  At that point, we will be able to display the grid pattern if we want (like in combat).

**Comment by jabelch** [comment]
Also, our whole methodology of generating the world on the fly goes along with not storing them to disk.  Each time we load a pane, it isn't going to be that much extra overhead to generate these images for that pane.

**Comment by basepi** [comment]
I would really like to avoid having that much interaction between world generation and graphics, though.  (But I'm willing to be flexible if it's important to you)  But I _definitely_ want to avoid storing actual image data in the tiles themselves -- way inefficient, unless every tile is unique, in which case that's going to be quite inefficient itself, which worries me.  Drawing that many different images to the screen could have quite a bit of overhead.  (Haven't tested to that effect, though)  Having a set of maybe 10-15 tile sprites for a background and then randomly dropping them into the different tiles I think would increase our efficiency quite a bit.

Also, is that image generation code working yet?  Because that's not somewhere we should put much debugging time at this point.  _Much_ more important to have a working World representation (and maybe even some world generation) and get as far as we can on that before Alpha.  Just saying.

**Comment by basepi** [comment]
This is no longer an issue, after meeting today with @jabelch.  Party on.
