### ISSUE TITLE
Cursed and unidentified Items

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#8]
I have proposed a system for identification of items and details on cursed items.  I would like feedback on the cursed item system both based on the feasibility of implementing it and the appeal overall.  

There is a two-part question at the bottom of the Cursed Items page representing this "issue".

https://github.com/basepi/akintu/wiki/Cursed-Items

@basepi , @jabelch , @Jzar

**Comment by malikoth** [comment]
I would change Oil of Identification to Scroll of Identification.  I can't imagine myself wanting to identify an unknown item, and thus covering its surface with oil.  Just seems weird to me.  I would say consumables cannot be cursed, they are simply useful (helpful) or not (detrimental).  Once you've identified which one it is, you can keep it or throw it away, rather than transmuting it into something completely unrelated to what it was originally created to do.  Incidentally, you could always dip your arrows or shuriken in a cursed potion to convey that effect to the target.

I would say just set a duration for each curse, and have it constant.  Have curse removal require some kind of investment by the character, much more than merely identifying the item.  Then most players should be able to get new items identified somehow, but not everyone can (or would want to) go to the bother of decursing things.  They have to make a decision to just equip it and live with the curse or not.

And with that, I have some thinking to do about character resources.

**Comment by BlackVegetable** [comment]
Alright.  I was thinking that you could equip unidentified items and that was why it had a different penalties.  You are suggesting that you cannot equip something that is unidentified, right?

**Comment by malikoth** [comment]
No, I didn't mean to imply anything like that.  Just that if you can't or don't want to identify an item, then equipping it blindly is just as much a risk as it is in other roguelikes.

**Comment by BlackVegetable** [comment]
Ah, then the importance of identifying an item is very minor.  That's fine.  Or are these cursed debuffs going to be rather severe some of the time?

**Comment by basepi** [comment]
I agree with what Kyle's been saying.  As far as whether unidentified items should be equippable, I don't much care.  However, if they can be, I think curses should roll fairly severe, so as to make identification more attractive.  Or not.  It doesn't really matter to me.

**Comment by jabelch** [comment]
I can't say I would want every curse to have the same duration with only the severity increasing.  Some curses might be weak (maybe takes only a few xp or some other attribute - decreased aim, health capacity, etc...), but last a long time or have super powerful curses take away things in extreme but only last a short while.  These could occur in any combination and length (with limits of course).
Maybe have a curse that slowly drains your health until you have a sliver left... and that is the only way it goes away.  Attempts to replenish your health prior to it running its course would be useless.

**Comment by jabelch** [comment]
What if we had an option to extract a curse?  Essentially certain characters would be able to extract a curse from an identified item or book and then use them as weapons - like the dipping arrows in cursed potion idea.  This could be a class of character on its own - the entire range of curses could be used as weapons.  And it would be a useful team character to have someone specialize in identifying and extracting curses.

**Comment by malikoth** [comment]
I definitely like the idea of having lots of variety in our curses.  We
could define a list of curse types, then leave the actual numbers blank.
Then just have the engine fill in the severity and duration according to
the formula Severity x Duration = C where c is some constant determined
through experimentation.

**Comment by malikoth** [comment]
The problem with having a class based around extracted curses would be
supply.  New items aren't precisely rare, but neither can you just find a
new cursed item kicking around the corridors every time you look down.
While we can tweak item drop rate, and curse occurance rates, that could be
a little annoying for the rest of the classes.

**Comment by jabelch** [comment]
I guess an entire class wouldn't be feasible, but it might go more along the lines of a wizard.  New curses could be learned from cursed items, but that would be just one source of experience.
Maybe this would be the special wizard/wizard ability.  just a thought

**Comment by basepi** [comment]
I think I would avoid the extracting-curses thing.  And ya, I like setting the severity of the curse from the RNG and a constant, and then generating the numbers so that between the duration and intensity of the curse we reach our severity level.  Two curses of the same severity might be very different -- one very intense but short, one very long but not very intense.

Also, cursed items should be rare-ish, as @Jzar said.

Again, my opinions.

**Comment by BlackVegetable** [comment]
Extracting curses would be a little complex -- a tertiary feature perhaps?  

Curses and unidentified items in general will be rare.

Having the severity and the length inversely proportional is an excellent idea.

I'll start up a list of curses and add it to the wiki at some point soon.

Everyone agree on these items? (Can we close the issue?)

**Comment by basepi** [comment]
Ya, the inversely-preportional thing will apply to almost all item generation (I think).  An item will have a generated quality number, and then the other stats will "add up to" this number.

**Comment by malikoth** [comment]
I think unidentified items should be equippable, and I agree with Colton that that means the curses should be fairly severe.
