### ISSUE TITLE
Should Double-Classes be allowed?

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#9]
Josh and Colton approved of our (mostly your) great idea for a class system, Kyle.  They were in favor of something that I am neutral regarding:

We should have doubled up classes allowed.  That is, Fighter/Fighter = Barbarian or Thief/Thief = Pickpocket or Ranger/Ranger = Sniper or Wizard/Wizard = Sorceror .  

They would have a large penalty for not having any secondary skills to choose from their second class but would still have unique abilities via combination abilities.  I proposed that on character selection, these classes be discouraged via a warning screen or message indicating they are not recommended combinations and are only for players looking for a challenge.

What are your thoughts @Jzar? Also, did I express your thoughts accurately @basepi  and @jabelch ?

**Comment by malikoth** [comment]
I like letting the player make informed choices.  So if he wants to commit to a less diverse character class, let it be on his head.

However, this is a non-issue if the player can change his secondary class selection while playing.  I have some thoughts on that topic for to put in a new issue.  More to come soon.

**Comment by basepi** [comment]
@Jzar well, I think we should definitely have some sort of Ironman mode (see the respeccing thread for that term), so it's a little bit of an issue.

In the end, I don't care either way, it would just be fairly trivial to implement and would allow for more variety.

**Comment by jabelch** [comment]
Perhaps there would be a minor penalty for switching classes.  This would promote sticking with your character longer.  Maybe the ironman mode would still allow a change, but it would be so costly you just don't do it on a whim.

**Comment by malikoth** [comment]
Alright, I'm sold.  Since I'm all about allowing the player his own
choices, and the double-class option fits that motif.  If he's got Ironman
checked, and selects a double-class, maybe pop up a dialog or confirmation
box?  Or just have a note at the bottom of the window? indicating that you
will lack the diversity of the hybrid classes.

**Comment by jabelch** [comment]
yes, ironman should mean just that.  if you hate it so much, go kill yourself in some interesting way and start over.

I still think a minor penalty might be useful for the hybrid classes though.

**Comment by malikoth** [comment]
I tell you, the most valuable class I think I've taken in college was not a
CS class, it was Econ 101, which is fundamentally the study of what
motivates people.  Understanding markets is all about understanding
incentives.  Now, if we put a penalty on hybrid classes for balance's sake,
then we're dis-incentivizing people to play the hybrids.  Since I think the
hybrids are going to be the most interesting and fun classes, I think that
would be detrimental to our game.  I wouldn't mind giving the
double-classes (I keep calling them "Purebloods" in my head, lol) a bonus
to compensate for their lack of diversity.  I like the message that this
sends of "This class is a little sub-par without this bonus, you stand
warned"  But I don't want to discourage people from playing the hybrids by
any means.

**Comment by jabelch** [comment]
hmm, mudbloods vs purebloods - the "holier than thou because I don't change and I'm so awesome" vs "this game is fan-friggin-tasticly fun to play"
Excuse my horrible-horrible excuse for what I call english and inconsistent capitalization. 

I find myself agreeing with you here - at least about going too far.  There will be limits (like only allowing the change in towns or the like) so it's a matter of deciding a reasonable limit vs. complete player customization.  If we want to allow total customization, we have to find a good set of defaults to be the limit that _most_ people will want to play so they don't muck around in the menus for 2 hours just to try it out. Conversely, it stands that we want the hardcore guys to have full control over their gameplay and they can take as long as they want in those menus.

That then takes us to multiplayer - what I've seen on client hosted games is that the host picks the game parameters and everyone else complies.  This might pose a problem to total customization that applies to a character - as certain choices could impact characters enough to create inconsistencies in multiplayer.  Maybe the strictest rules out of all apply to the whole group...

**Comment by basepi** [comment]
Nah, you just have all the world rules come from the host, and everyone keeps their own specific character rules.  Limiting people based on the host (or removing those limits) goes against our "play how you want" idea, and might frustrate users to boot.  If people want to match their limits, create a new toon with those limits.

Also, there should be no penalty for hybrid classes, like Kyle said.  Ideally, every class combination should be equally attractive.

Those are my opinions, anyway.

**Comment by BlackVegetable** [comment]
If there is any penalty, it will be with the double-classes.  Hybrids should be thought of as the standard classes.  

Hosts can choose to allow or disallow players who have or don't have hardcore or other flags set on their own.  That is, we won't code anything up other than an indicator as to which settings that character has.  Hosts will set world rules and stuff like the time limit for each turn etc. 

Can we consider this one closed?

**Comment by basepi** [comment]
Sounds fine to me.

**Comment by malikoth** [comment]
Yes.  (And though I liked the D3 model of changing stuff up at any time, I think requiring the player to be in town to change secondaries is fine.  It worked in GW1 and made you think about what you want ahead of time, even if you're not committing to it as completely as Ironman chars are)
