### ISSUE TITLE
Skeleton Key

### ISSUE THREAD

**Issue by BlackVegetable** [akintu/akintu#93]
Would we like to (eventually) have a rare item called the skeleton key exist that can open any treasure chest without requiring lockpicking skill or bashing the chest (and risking damage to the contents)?

It would have a one-time only use, and could not be purchased in stores perhaps. @Jzar  would probably have the most to say on this issue.

**Comment by malikoth** [comment]
Personally, I never really liked the lockpicking mechanics in The Elder Scrolls or anything, and I believe chests should have a reasonable chance of yielding their highest level gear.  So I'd go with something like, 50/50 chance to even be locked in the first place, and if you bash it, 50/50 chance to damage the contents.  Or 66/33 for a 1/3 chance of degraded loot.  Anyways, if we did something like that, then a skeleton key wouldn't make a huge difference whether it's there or not.  If it's not too much trouble to code, then go for it.  Otherwise, I'd say don't bother and put your time into more visible things.  Just my $0.02.  Sorry it took me so long to check in on my unread notifications!

**Comment by BlackVegetable** [comment]
The chance of being locked was going to be 20%.  And bashing mechanics are kinda neat (they're on the wiki).  Lockpicking will always work if you have enough skill.  But with only 20% of chests being locked, I don't think damaged gear will ruin anyone's fun.

**Comment by malikoth** [comment]
Then I say don't bother with something that's such a low impact as a skeleton key.

**Comment by BlackVegetable** [comment]
Alright, I'll focus on more important things.
